//
// Created by Conner Morton on 11/30/2020.
//

#ifndef SEARCH_ENGINE_LIN_MORTON_SEARCHENGINE_H
#define SEARCH_ENGINE_LIN_MORTON_SEARCHENGINE_H


class SearchEngine {

};


#endif //SEARCH_ENGINE_LIN_MORTON_SEARCHENGINE_H
